### PR TITLE
Changed bits download bucket to k8s-release-dev

### PR DESCRIPTION
**Pull request by Rajalakshmi-Girish**
Changing the k8s bits download bucket to `k8s-release-dev`. Verified if the changed bucket is working fine by not passing the bucket details and letting it **pick up default value from** `group_vars/all`
```
AzureAD+RajalakshmiGirish@DESKTOP-OBNPTCK ~/k8s-ansible
$ ansible-playbook -i examples/stable-cluster/hosts.yml install-k8s.yml --extra-vars "@examples/stable-cluster/extra-vars-k8s-stable.json" -e 'ansible_ssh_transfer_method=scp'
 [WARNING]: Could not match supplied host pattern, ignoring: workers


PLAY [Install Runtime and Kubernetes] **********************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************
ok: [158.175.161.133]

TASK [runtime : Install crictl] ****************************************************************************************************************************************************************
ok: [158.175.161.133]

TASK [runtime : Add OpenPower repository] ******************************************************************************************************************************************************
ok: [158.175.161.133]

TASK [runtime : Install iptables] **************************************************************************************************************************************************************
ok: [158.175.161.133]

TASK [runtime : Add OpenPower repository] ******************************************************************************************************************************************************
ok: [158.175.161.133]

TASK [runtime : Install Docker] ****************************************************************************************************************************************************************
ok: [158.175.161.133]

TASK [runtime : Create a /etc/docker dir] ******************************************************************************************************************************************************
ok: [158.175.161.133]

TASK [runtime : Template a docker config to /etc/docker/daemon.json] ***************************************************************************************************************************
ok: [158.175.161.133]

TASK [runtime : Enable and start docker] *******************************************************************************************************************************************************
changed: [158.175.161.133]

TASK [runtime : Create a /etc/systemd/system/kubelet.service.d dir] ****************************************************************************************************************************
ok: [158.175.161.133]

TASK [runtime : Create docker drop-in file for kubelet service] ********************************************************************************************************************************
ok: [158.175.161.133]

TASK [runtime : Flush the iptable rules] *******************************************************************************************************************************************************
changed: [158.175.161.133]

TASK [runtime : Restart docker] ****************************************************************************************************************************************************************
changed: [158.175.161.133]

TASK [runtime : Install containerd] ************************************************************************************************************************************************************
skipping: [158.175.161.133]

TASK [runtime : Load kernel modules] ***********************************************************************************************************************************************************
skipping: [158.175.161.133] => (item=overlay)
skipping: [158.175.161.133] => (item=br_netfilter)

TASK [runtime : Sysctl settings] ***************************************************************************************************************************************************************
skipping: [158.175.161.133] => (item=net.bridge.bridge-nf-call-iptables)
skipping: [158.175.161.133] => (item=net.ipv4.ip_forward)
skipping: [158.175.161.133] => (item=net.bridge.bridge-nf-call-ip6tables)

TASK [runtime : Create a /etc/containerd dir] **************************************************************************************************************************************************
skipping: [158.175.161.133]

TASK [runtime : Generate /etc/containerd/config.toml] ******************************************************************************************************************************************
skipping: [158.175.161.133]

TASK [runtime : Create a /etc/systemd/system/kubelet.service.d dir] ****************************************************************************************************************************
skipping: [158.175.161.133]

TASK [runtime : Create containerd drop-in file for kubelet service] ****************************************************************************************************************************
skipping: [158.175.161.133]

TASK [runtime : Restart containerd] ************************************************************************************************************************************************************
skipping: [158.175.161.133]

TASK [download-k8s : Extract the k8s bits] *****************************************************************************************************************************************************
ok: [158.175.161.133] => (item=kubernetes-test-linux-ppc64le.tar.gz)
changed: [158.175.161.133] => (item=kubernetes-client-linux-ppc64le.tar.gz)
changed: [158.175.161.133] => (item=kubernetes-server-linux-ppc64le.tar.gz)

TASK [download-k8s : debug] ********************************************************************************************************************************************************************
ok: [158.175.161.133] => {
    "msg": "BUCKET NAME k8s-release-dev DONE"
}

TASK [install-k8s : Disable SWAP since kubernetes can't work with swap enabled (1/2)] **********************************************************************************************************
changed: [158.175.161.133]

TASK [install-k8s : Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)] *************************************************************************************************
ok: [158.175.161.133]

TASK [install-k8s : Install prereq packages] ***************************************************************************************************************************************************
ok: [158.175.161.133]

TASK [install-k8s : Template a kubelet service to /usr/lib/systemd/system/kubelet.service] *****************************************************************************************************
ok: [158.175.161.133]

TASK [install-k8s : Enable and start kubelet] **************************************************************************************************************************************************
changed: [158.175.161.133]

TASK [install-k8s : Generate kubeadm.yaml] *****************************************************************************************************************************************************
ok: [158.175.161.133]

TASK [install-k8s : kubeadm init] **************************************************************************************************************************************************************
changed: [158.175.161.133]

TASK [install-k8s : Create a directory ${HOME}/.kube if it does not exist] *********************************************************************************************************************
changed: [158.175.161.133]

TASK [install-k8s : Copy the /etc/kubernetes/admin.conf to ${HOME}/.kube/config] ***************************************************************************************************************
changed: [158.175.161.133]

TASK [install-k8s : Copy the /etc/kubernetes/admin.conf to local machine(path - kubeconfig)] ***************************************************************************************************
changed: [158.175.161.133]

TASK [install-k8s : remove taint] **************************************************************************************************************************************************************
changed: [158.175.161.133]

TASK [install-k8s : Get the kubeadm join command from the Kubernetes master.] ******************************************************************************************************************
ok: [158.175.161.133]

TASK [install-k8s : Set the kubeadm join command globally.] ************************************************************************************************************************************
ok: [158.175.161.133 -> 158.175.161.133] => (item=158.175.161.133)

TASK [install-k8s : kubeadm join] **************************************************************************************************************************************************************
skipping: [158.175.161.133]

PLAY [Install networking - calico] *************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************
ok: [158.175.161.133]

TASK [install-calico : Download calico manifest] ***********************************************************************************************************************************************
changed: [158.175.161.133]

TASK [install-calico : Set veth_mtu] ***********************************************************************************************************************************************************
changed: [158.175.161.133]

TASK [install-calico : kubectl] ****************************************************************************************************************************************************************
changed: [158.175.161.133]

PLAY RECAP *************************************************************************************************************************************************************************************
158.175.161.133            : ok=32   changed=14   unreachable=0    failed=0    skipped=9    rescued=0    ignored=0


AzureAD+RajalakshmiGirish@DESKTOP-OBNPTCK ~/k8s-ansible
```

### CODE REVIEW

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/k8s-ansible/pull/12#" title="Author self-approved">Rajalakshmi-Girish</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **mkumatag** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @mkumatag` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Fk8s-ansible).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ppc64le-cloud/k8s-ansible/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by mkumatag — APPROVED** [review]
/lgtm

**Comment by ltccci** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ppc64le-cloud/k8s-ansible/pull/12#pullrequestreview-620674114" title="LGTM">mkumatag</a>*, *<a href="https://github.com/ppc64le-cloud/k8s-ansible/pull/12#" title="Author self-approved">Rajalakshmi-Girish</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ppc64le-cloud%2Fk8s-ansible).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/ppc64le-cloud/k8s-ansible/blob/master/OWNERS)~~ [mkumatag]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by mkumatag** [comment]
@Rajalakshmi-Girish after this merge, please update the submodule as well in the kubetest2-plugin project, more info - https://github.com/ppc64le-cloud/kubetest2-plugins#update-the-submodule

**Pull request merged**
